In [8]:
import pandas as pd
# from pil import Image
from ipywidgets import interact
import matplotlib.pyplot as plt
import numpy as np
import os

%matplotlib widget

In [9]:
proposal = 20240661
visit = 2024102408
folder = '/data/visitors/formax/%s/%s/process' % (proposal, visit)

logfile = 'logbook_227.csv'
df = pd.read_csv(os.path.join(folder,logfile), sep=';')
df

# drop empty columns
df = df.dropna(axis=1, how='all')
df

,Name,ScanNbr,Direction,RH [%],Force [N],Time,Comment
0,Test_SD_MD_50,29,MD,50.0,5.0,5.0,Test sample
1,Test_SD_MD_50,30,MD,50.0,10.0,5.0,Test sample
2,Test_SD_MD_50,31,MD,50.0,15,5.0,Test sample
3,Test_SD_MD_50,32,MD,50.0,20,5.0,"Test sample, broke before reaching 20 N"
4,01_SD_MD_50,33,MD,50.0,NaN,NaN,Realignment
...,...,...,...,...,...,...,...
194,22_DDH_45_50,223,NaN,50.0,NaN,NaN,NaN
195,22_DDH_45_50,224,NaN,50.0,NaN,NaN,NaN
196,22_DDH_45_50,225,NaN,50.0,2,NaN,NaN
197,22_DDH_45_50,226,NaN,50.0,4,NaN,NaN
198,22_DDH_45_50,227,NaN,50.0,6,NaN,NaN

In [12]:
def show_image(scan_nr):
    image_folder = os.path.join(folder, 'images')
    filename = 'tot_scatter_scan_%i.png' % scan_nr
    print(filename)
    img = plt.imread(os.path.join(folder, filename))
    plt.imshow(img)
    plt.show()

interact(show_image, scan_nr=(0, 100, 1));

interactive(children=(IntSlider(value=50, description='scan_nr'), Output()), _dom_classes=('widget-interact',)…